### PR TITLE
Add subscription to payment on payment method change.

### LINKED ISSUE #44: Payment method changes don't update subscription mandate
It seems that payment method changes via WooCommerce don't update the mandate anymore in the Pronamic subscription. This is probably due to the payment for the method change not being linked to any subscriptions.

No Pronamic subscriptions are returned by `Gateway::get_pronamic_subscriptions()` if the passed `$order` is an instance of `\WC_Subscription`.

https://github.com/pronamic/wp-pronamic-pay-woocommerce/blob/05be2c3cf23cd3b2488606e9aa8007c993ac1136/src/Gateway.php#L385-L392

https://github.com/pronamic/wp-pronamic-pay-woocommerce/blob/05be2c3cf23cd3b2488606e9aa8007c993ac1136/src/Gateway.php#L711-L737

### PR DESCRIPTION
**Pull request by rvdsteege**
Fix #44.

### CODE REVIEW

**Comment by remcotolsma** [comment]
Wouldn't this be better handled here:

https://github.com/pronamic/wp-pronamic-pay-woocommerce/blob/5628f74cd24f162bfacc3b649f6a233dd5c34608/src/Gateway.php#L749C1-L772

```php
if ( $order instanceof \WC_Subscription ) {
    $woocommerce_subscriptions[] = $order;
}
```

**Comment by rvdsteege** [comment]
> Wouldn't this be better handled here […]

@remcotolsma I'm afraid I don't see how exactly... 🤔

**Comment by remcotolsma** [comment]
@rvdsteege like this?

```php
	/**
	 * Connection subscription payment renewal.
	 *
	 * @param Payment  $payment Payment.
	 * @param WC_Order $order   WooCommerce order.
	 * @return void
	 */
	private function connect_subscription_payment_renewal( $payment, $order ) {
		if ( ! \function_exists( '\wcs_get_subscriptions_for_order' ) ) {
			return;
		}

		$woocommerce_subscriptions = \wcs_get_subscriptions_for_order( $order, [ 'order_type' => 'renewal' ] );

		// 👇 @rvdsteege like this?
		if ( $order instanceof \WC_Subscription ) {
 		   $woocommerce_subscriptions[] = $order;
		}

		foreach ( $woocommerce_subscriptions as $woocommerce_subscription ) {
			$subscription_helper = new SubscriptionHelper( $woocommerce_subscription );

			$pronamic_subscription = $subscription_helper->get_pronamic_subscription();

			if ( null !== $pronamic_subscription ) {
				$payment->add_subscription( $pronamic_subscription );
			}
		}
	}
```

**Comment by rvdsteege** [comment]
Hmm, I thought I had tested that and that it somehow resulted in unwanted changes to the Pronamic subscription. Tried again and seems fine indeed, I probably added the lines somewhere else (maybe in `Gateway::get_pronamic_subscriptions()`?). Merging now.

**Pull request merged**
