### PR TITLE
Add Pronamic Pay meta box to WooCommerce subscription admin page

### PR DESCRIPTION
**Pull request by remcotolsma**
Scherm­afbeelding 2023-09-18 om 16 26 27

### CODE REVIEW

**Review by rvdsteege — COMMENTED** [review]
Should this meta box not link to / give details about the corresponding Pronamic Pay subscription instead of a payment (which is only linked through the `_pronamic_payment_id` meta with payment method changes)?

**Comment by remcotolsma** [comment]
Yes, good question. In the case of a customer's payment method change, it may be useful to see a direct reference to the last (micro) payment for such a change. A direct reference to the Pronamic Pay subscription can also be useful for other administrative work. Expand it so that both data are shown? Should we split it into 2 separate meta boxes "Pronamic Pay Payment" and "Pronamic Pay Subscription" or should we bundle this into one "Pronamic Pay" meta box? What do you think is the most useful @rvdsteege?

**Comment by rvdsteege** [comment]
> Should we split it into 2 separate meta boxes "Pronamic Pay Payment" and "Pronamic Pay Subscription" or should we bundle this into one "Pronamic Pay" meta box? What do you think is the most useful @rvdsteege?

I think "Pronamic Pay Subscription" meta box is sufficient. The updated payment method usually doesn't matter much?

**Comment by remcotolsma** [comment]
> > Should we split it into 2 separate meta boxes "Pronamic Pay Payment" and "Pronamic Pay Subscription" or should we bundle this into one "Pronamic Pay" meta box? What do you think is the most useful @rvdsteege?
> 
> I think "Pronamic Pay Subscription" meta box is sufficient. The updated payment method usually doesn't matter much?

It feels a bit more complete to also show the latest payment information. I think that is also nice for administrative issues. If customers have questions about their order/subscription, it is useful to have the latest payment information immediately visible. I have added this in 9e92e29fb5a552918268f2669534eaa94e312c4b, awaiting review from @rvdsteege.

**Review by rvdsteege — APPROVED** [review]

**Pull request merged**
